postgresAlpDBConnectionURL=jdbc:postgresql://dev-database-postgres.cx8e6yki66z5.ap-south-1.rds.amazonaws.com:5432/Testing_glass_DB
postgresDriverClass=org.postgresql.Driver
pgUserName=postgres
pgPassword=Admin123
sqlDriverClass=com.microsoft.sqlserver.jdbc.SQLServerDriver
